# Generated by Django 2.2.2 on 2020-02-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200229_1910'),
        ('core', '0006_auto_20200229_1909'),
    ]

    operations = [
    ]
