# Generated by Django 3.0.3 on 2020-03-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20200303_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='slug',
            field=models.SlugField(default='/', unique=True),
        ),
    ]
