# Generated by Django 3.0.3 on 2020-03-04 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0016_auto_20200303_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='slug',
            field=models.SlugField(default=False, unique=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.Book'),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
