# Generated by Django 3.0.3 on 2020-03-04 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20200304_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='slug',
            field=models.SlugField(default=False),
        ),
    ]
